version: '3.7'

services:
  db:
    image: postgres:15
    container_name: task_tracker_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env-non-dev
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env-non-dev
    container_name: task_tracker_cont
    command:
      - "docker/app.sh"
    ports:
      - "7777:8000"
    depends_on:
      - db

volumes:
  postgres_data:









